### ISSUE TITLE
Monthly Report

### ISSUE THREAD

**Issue by nixnull** [AgoraNomic/Registrar#1]
I have a little work done on the monthly report - a .csv with some of the historical records, and a not-yet functional script to generate a table based on that. I'll throw them into a Monthly folder in this repo and then we can both work on it until the records are caught up and the script looks nice, if that's all acceptable to you.

P.S. what scripting language are you most comfortable with? I usually use python for these things but ruby would work just as well if you prefer.

**Comment by PubliusScriboniusScholasticus** [comment]
Sorry for not seeing this until now. I am comfortable with python or ruby, so I'm fine with either.

**Comment by randomnetcat** [comment]
Appears to be abandoned, and Falsifian has completely changed the form of the reports - closing
